all:
	nvcc -arch=sm_80 -o bin/atomic_add_half_pack2 atomic_add_half_pack2.cu
	nvcc -arch=sm_80 -o bin/atomic_add_half atomic_add_half.cu
	nvcc -arch=sm_80 -o bin/fast_atomic_add_half fast_atomic_add_half.cu


